### ISSUE TITLE
Training on my own split

### ISSUE THREAD

**Issue by Amor-ZYF** [md4all/md4all#30]
Hi! I want to train the model on my own split for RobotCar. What should I do to prepare the necessary files? 

I have taken the following steps, but the training result seems bad.

1. run the precompute_rgb_images.py to get the RGB images.
2. run the precompute_pose_gt.py,  replacing the timestamps_path with my train_files.txt and val_files.txt.
3. run the precompute_depth_gt.py, replacing the timestamps_path with my val_files.txt, saving the .pcd.bin files.
4. run the filter_overexposed_static_images.py, using the .json file generated in [2.] and my train_files.txt and val_files.txt.
5. in the file robotcar_dataset.py file, change the split path to my split files and do relevant changes in the train_baseline_robotcar.yaml.
6. run train.py

Would you please point out where I might have made mistakes, or where else I need to make changes.
Thanks a lot! :)

**Comment by morbi25** [comment]
Hi @Amor-ZYF,

Thank you for reaching out again! :)

At first glance, this procedure sounds reasonable. However, it has been a while since I wrote and used the code of these procedures.

Could you maybe specify what kind of split you use for training and validation. How large is your training set? What types of samples do your training and validation split contain (i.e. day or night samples)? Besides that, could you also clarify what you mean by "the training result seems bad"? And especially could you also check the quantitative results when the ground truth mean scaling is applied when evaluating the baseline?

Furthermore, you should double-check the results produced in every step when preparing your data. For example, check that the projection of the point clouds to the images of your split looks reasonable. Besides that, could you please double-check and share how the tensorboard visualizations look for your training?

I hope this helps you! Have a nice day! :)
