### ISSUE TITLE
Questions w.r.t the code and method

### ISSUE THREAD

**Issue by w2kun** [md4all/md4all#8]
Hi, thank you for sharing your code. Your work is very interesting and impressive. I have three questions about the code and the method that I would like to ask you:

1. In your paper, you proposed using percentage `x` to blend input images under different weather conditions. Could you please point me to the code that implements this part? I did not find it in the repository.
2. You use NormalizeDynamic’s daytime mode in DD stage to normalize the input. This normalization requires input of the corresponding weather conditions (e.g. day or night). Does this mean that correct weather is also required during evaluation?
3. You used four modes (‘’, ‘_pp’, ‘_gt’, ‘_pp_gt’) in the evaluator to evaluate depth estimation. What is the post-process represented by pp used for? Which mode did you use for the results you reported in your paper?

I would appreciate it if you could answer my questions or provide some guidance. Thank you for your time and attention. I look forward to hearing from you soon.

**Comment by sgasperini** [comment]
Hi @w2kun,

Thank you very much! We really appreciate your interest in our work.

1. The x% regulates the amount of translated images, and in the code that happens in the function linked [here](https://github.com/md4all/md4all/blob/01083e845edbd71f16e14aa7b904228c1a538d87/data/transforms.py#L232). The amount is specified in the configuration files (e.g., [here](https://github.com/md4all/md4all/blob/01083e845edbd71f16e14aa7b904228c1a538d87/config/train_md4allDDa_nuscenes.yaml#L17)).

2. The time-dependent normalization aims to learn a common representation between night and day. However, it is not dependent on the weather (i.e., day-clear and day-rain share the same). At training time, we align the distributions by normalizing according to the time of the day (i.e., different mean and std between night and day). Instead, in the supplementary material (e.g., A15 in Table 4), we show how the time-dependent normalization does not have an impact at inference time, meaning that inference can be made similarly with the standard, fixed normalization parameters (i.e., the same mean and std for both night and day). Additionally, after the submission, we noticed that the image-dependent normalization is performing similarly, too (i.e., mean and std dependent on the individual image in input), and that is also in the code. Intuitively, this can be explained considering the model has already learned a common representation at training time between the nighttime and daytime distributions, such that the normalization applied at inference time is not critical. You can find additional details in the supplementary material (e.g., where we discuss A15 in Section A.3.1).
To sum up, you can infer with fixed normalization parameters for all inputs or with normalization parameters dependent on each individual input without really affecting the output. Therefore, having such time-dependent information at inference time is not required.

3. As explained [here](https://github.com/TRI-ML/packnet-sfm/issues/85#issuecomment-712246427) by the author of PackNet-SfM, `pp` applies a simple test-time augmentation by inferring on the original and the flipped images, and combining the outputs. Instead, `gt` uses the ground truth median scaling (e.g., via the LiDAR ground truth data). Then, `pp_gt` does both. In particular, we report the `pp` values for all models despite the minimal difference between `pp` and the standard. Additionally, for those models that are not scale-aware (indicated by a * in Tables 1 and 2 of the paper, e.g., Monodepth2), we apply the necessary ground truth scaling on top, so we report `pp_gt` for such methods. For example, we do not use `gt` scaling for ours because ours has the advantage of being scale-aware thanks to the weak velocity supervision introduced by PackNet-SfM, so for md4all, we report `pp`.

We hope this helps clear up your doubts. Please let us know if you have any questions about these or other points.

**Comment by w2kun** [comment]
Thanks for your prompt and detailed reply! I am closing this issue.
